version: '3.0'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
    volumes:
      - ./data/esnode0:/usr/share/elasticsearch/data
    restart: always
    
  parsedmarc:
    container_name: parsedmarc
    image: bongoeadgc6/parsedmarc:stable
    links:
      - elasticsearch
    command: tail -f /dev/null
    volumes:
      - ./config/parsedmarc.ini:/etc/parsedmarc.ini:ro
    restart: always

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.3.1
    links:
      - elasticsearch
    environment:
      - SERVER_NAME=dmarcanalyzer.fqdn
      - VIRTUAL_HOST=dmarcanalyzer.fqdn
      - VIRTUAL_NETWORK=proxy-ssl
      - VIRTUAL_PORT=5601
      - CERT_NAME=shared

    restart: always
    networks:
      - default
      - front
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dmarcanalyzer.entrypoints=http-internal"
      - "traefik.http.routers.dmarcanalyzer.rule=Host(`dmarcanalyzer.fqdn`)"
      - "traefik.http.services.dmarcanalyzer.loadbalancer.server.port=5601"

networks:
  front:
    external:
      name: traefik-portainer_default
