version: '3'

services:
  nginx:
    build: ./nginx/
    container_name: phpipam_nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/:/etc/certs
      - ./conf/ipam.local:/etc/nginx/sites-available/ipam.local
    links:
      - ipam
    networks:
      - default
      - traefik
  ipam:
    image: pierrecdn/phpipam:1.4
    container_name: phpipam
    environment:
      - MYSQL_ENV_MYSQL_HOST=10.80.8.101
      - MYSQL_ENV_MYSQL_USER=phpipam
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=password
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.phpipam.entrypoints=http-internal"
     - "traefik.http.routers.phpipam.rule=Host(`ipamlocal`)"
     - "traefik.http.services.phpipam.loadbalancer.server.port=80"

networks:
  traefik:
    external:
        name: traefik-portainer_default
